/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.ScrollPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Cadidato;
import modelos.CandidatoBO;

/**
 *
 * @author Ezeks
 */
public class ControleCandidatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControleCandidatos
     */
    public ControleCandidatos() {
        initComponents();
        DefaultTableModel modeltable = (DefaultTableModel) tabelacandidatos.getModel();
        tabelacandidatos.setRowSorter(new TableRowSorter(modeltable));
        preencherTabela();
        
        //ESTILIZAÇÃO DOS BOTÕES
        
        /*jButton4.setFont(new Font("Ravie", 1, 18));
        jButton4.setForeground(new Color(105,105,105));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton4.setRequestFocusEnabled(false);
       jButton4.setRolloverEnabled(false);
       jButton4.setMargin(new Insets(2, 1000, 2, 14));
       
       jButton5.setFont(new Font("Ravie", 1, 18));
        jButton5.setForeground(new Color(105,105,105));
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton5.setRequestFocusEnabled(false);
       jButton5.setRolloverEnabled(false);
       jButton5.setMargin(new Insets(2, 1000, 2, 14));
       
       jButton6.setFont(new Font("Ravie", 1, 18));
        jButton6.setForeground(new Color(105,105,105));
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,149,237), 3));
        
        jButton6.setRequestFocusEnabled(false);
       jButton6.setRolloverEnabled(false);
       jButton6.setMargin(new Insets(2, 1000, 2, 14));
        */
        
    }
    
    
    public void preencherTabela(){
        
        DefaultTableModel modeltable = (DefaultTableModel) tabelacandidatos.getModel();
         modeltable.setNumRows(0);
         CandidatoBO candidatobo = new CandidatoBO();
         
         for (Cadidato candidato: candidatobo.consulta()){
             modeltable.addRow(new Object[]{
             candidato.getNome(), candidato.getCpf(), candidato.getEmail(), candidato.getIdade(), candidato.getTelefone()
             });
         }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacandidatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nascimento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        curso = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        experiencia = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        uf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setTitle("Candidate Control");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/interface3.png"))); // NOI18N

        tabelacandidatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelacandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Cpf", "Email", "Birth date", "Phone", "Genre", "Address", "Courses", "Experiences"
            }
        ));
        tabelacandidatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelacandidatos.setMinimumSize(new java.awt.Dimension(80, 80));
        tabelacandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelacandidatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacandidatos);
        if (tabelacandidatos.getColumnModel().getColumnCount() > 0) {
            tabelacandidatos.getColumnModel().getColumn(0).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(0).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(0).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(1).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(1).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(1).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(2).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(3).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabelacandidatos.getColumnModel().getColumn(3).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(4).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(4).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(4).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(5).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setMinWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setPreferredWidth(230);
            tabelacandidatos.getColumnModel().getColumn(6).setMaxWidth(230);
            tabelacandidatos.getColumnModel().getColumn(7).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(7).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(7).setMaxWidth(300);
            tabelacandidatos.getColumnModel().getColumn(8).setMinWidth(300);
            tabelacandidatos.getColumnModel().getColumn(8).setPreferredWidth(300);
            tabelacandidatos.getColumnModel().getColumn(8).setMaxWidth(300);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("List of all registered candidates");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        nome.setBackground(new java.awt.Color(240, 239, 253));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phone:");

        telefone.setBackground(new java.awt.Color(240, 239, 253));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        email.setBackground(new java.awt.Color(240, 239, 253));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address:");

        endereco.setBackground(new java.awt.Color(240, 239, 253));
        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Birth date:");

        nascimento.setBackground(new java.awt.Color(240, 239, 253));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Genre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CPF:");

        cpf.setBackground(new java.awt.Color(240, 239, 253));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Additional Information");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Courses:");

        curso.setBackground(new java.awt.Color(238, 237, 240));
        curso.setColumns(20);
        curso.setRows(5);
        curso.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jScrollPane2.setViewportView(curso);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Experiences:");

        experiencia.setBackground(new java.awt.Color(238, 237, 240));
        experiencia.setColumns(20);
        experiencia.setRows(5);
        experiencia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jScrollPane3.setViewportView(experiencia);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Personal informations");

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Register");
        jButton4.setMargin(new java.awt.Insets(3, 15, 3, 15));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Zip Code:");

        cep.setBackground(new java.awt.Color(240, 239, 253));
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Number:");

        numero.setBackground(new java.awt.Color(240, 239, 253));
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("UF:");

        uf.setBackground(new java.awt.Color(240, 239, 253));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo123.png"))); // NOI18N

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Delete");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculine", "Feminine", "Others" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(nascimento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cpf)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(11, 11, 11)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(11, 11, 11)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(11, 11, 11)
                                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(375, 375, 375))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(10, 10, 10)
                                    .addComponent(email)
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel4)
                                    .addGap(11, 11, 11)
                                    .addComponent(telefone)
                                    .addGap(127, 127, 127)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(64, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelacandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelacandidatosMouseClicked
        // TODO add your handling code here:
        //quando o o entrevistador clicar em uma linha da tabela
        int linha = this.tabelacandidatos.getSelectedRow();
        
        String nome1 = tabelacandidatos.getModel().getValueAt(linha, 0).toString();
        String cpf1 = tabelacandidatos.getModel().getValueAt(linha, 1).toString();
        String email1 = tabelacandidatos.getModel().getValueAt(linha, 2).toString();
        String idade1 = tabelacandidatos.getModel().getValueAt(linha, 3).toString();
        //int i = Integer.parseInt(idade1);
        //String telefone = tabelacandidatos.getModel().getValueAt(linha, 5).toString();
        
        this.nome.setText(nome1);
        this.cpf.setText(cpf1);
        this.email.setText(email1);
        this.nascimento.setText(idade1);
        //this.telefone.setText(telefone);
        
        
    }//GEN-LAST:event_tabelacandidatosMouseClicked

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOTAO DE CADASTRAR
        
        //VALIDAÇÃO DOS CAMPOS
        if(nome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The name field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(cpf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "CPF field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(email.getText().equals("")){
           JOptionPane.showMessageDialog(null, "The email field is required", "Warning", JOptionPane.WARNING_MESSAGE);
           return;
        }
        if(nascimento.getText().equals("")){
          JOptionPane.showMessageDialog(null, "The date of birth field is required", "Warning", JOptionPane.WARNING_MESSAGE);
          return;
        }
        if(telefone.getText().equals("")){
         JOptionPane.showMessageDialog(null, "The telephone field is required", "Warning", JOptionPane.WARNING_MESSAGE);
         return;
        }
        if(endereco.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Address field is required", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        if(curso.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The course field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(experiencia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The experience field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(cep.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The ZIP code field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(numero.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The number field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(uf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The UF field is required", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextArea curso;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextArea experiencia;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTable tabelacandidatos;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
